// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantRoller.API.Data;

#nullable disable

namespace RestaurantRoller.API.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250315185533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#E51A4B",
                            Description = "Italian cuisine",
                            DisplayOrder = 1,
                            IconName = "pizza",
                            IsActive = true,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#D90B6E",
                            Description = "Japanese cuisine",
                            DisplayOrder = 2,
                            IconName = "sushi",
                            IsActive = true,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#F44336",
                            Description = "American cuisine",
                            DisplayOrder = 3,
                            IconName = "burger",
                            IsActive = true,
                            Name = "American"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#FF9800",
                            Description = "Mexican cuisine",
                            DisplayOrder = 4,
                            IconName = "taco",
                            IsActive = true,
                            Name = "Mexican"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#FFC107",
                            Description = "Chinese cuisine",
                            DisplayOrder = 5,
                            IconName = "noodles",
                            IsActive = true,
                            Name = "Chinese"
                        });
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.OperatingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("OperatingHours");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("GoogleRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastVisited")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PriceRange")
                        .HasColumnType("int");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("YelpRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.5m,
                            City = "Anytown",
                            CreatedAt = new DateTime(2025, 3, 15, 18, 55, 33, 418, DateTimeKind.Utc).AddTicks(6668),
                            Cuisine = "Italian",
                            Description = "Authentic Italian pasta and pizza in a cozy atmosphere.",
                            GoogleRating = 4.3m,
                            IsActive = true,
                            Latitude = 34.0522m,
                            Longitude = -118.2437m,
                            Name = "Pasta Paradise",
                            PhoneNumber = "(555) 123-4567",
                            PriceRange = 2,
                            RatingCount = 120,
                            State = "CA",
                            StreetAddress = "123 Main St",
                            Website = "https://pastaparadise.example.com",
                            YelpRating = 4.2m,
                            ZipCode = "90210"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 4.8m,
                            City = "Anytown",
                            CreatedAt = new DateTime(2025, 3, 15, 18, 55, 33, 418, DateTimeKind.Utc).AddTicks(6674),
                            Cuisine = "Japanese",
                            Description = "Fresh sushi and sashimi prepared by master chefs.",
                            GoogleRating = 4.7m,
                            IsActive = true,
                            Latitude = 34.0548m,
                            Longitude = -118.2500m,
                            Name = "Sushi Sensation",
                            PhoneNumber = "(555) 234-5678",
                            PriceRange = 3,
                            RatingCount = 85,
                            State = "CA",
                            StreetAddress = "456 Oak Ave",
                            Website = "https://sushisensation.example.com",
                            YelpRating = 4.5m,
                            ZipCode = "90210"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 4.2m,
                            City = "Anytown",
                            CreatedAt = new DateTime(2025, 3, 15, 18, 55, 33, 418, DateTimeKind.Utc).AddTicks(6679),
                            Cuisine = "American",
                            Description = "Juicy burgers and crispy fries in a family-friendly setting.",
                            GoogleRating = 4.0m,
                            IsActive = true,
                            Latitude = 34.0575m,
                            Longitude = -118.2525m,
                            Name = "Burger Bonanza",
                            PhoneNumber = "(555) 345-6789",
                            PriceRange = 1,
                            RatingCount = 150,
                            State = "CA",
                            StreetAddress = "789 Elm Blvd",
                            Website = "https://burgerbonanza.example.com",
                            YelpRating = 3.9m,
                            ZipCode = "90210"
                        });
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.RestaurantCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 3, 15, 18, 55, 33, 418, DateTimeKind.Utc).AddTicks(6903),
                            IsPrimary = true,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 3, 15, 18, 55, 33, 418, DateTimeKind.Utc).AddTicks(6905),
                            IsPrimary = true,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 3, 15, 18, 55, 33, 418, DateTimeKind.Utc).AddTicks(6906),
                            IsPrimary = true,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("HomeAddressId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("WorkAddressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HomeAddressId");

                    b.HasIndex("WorkAddressId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.UserRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRatings");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Category", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.OperatingHours", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Restaurant", "Restaurant")
                        .WithMany("OperatingHours")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.RestaurantCategory", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Category", "Category")
                        .WithMany("RestaurantCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantRoller.API.Data.Entities.Restaurant", "Restaurant")
                        .WithMany("RestaurantCategories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Review", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantRoller.API.Data.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.User", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Address", "HomeAddress")
                        .WithMany("UsersWithHomeAddress")
                        .HasForeignKey("HomeAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestaurantRoller.API.Data.Entities.Address", "WorkAddress")
                        .WithMany("UsersWithWorkAddress")
                        .HasForeignKey("WorkAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HomeAddress");

                    b.Navigation("WorkAddress");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.UserFavorite", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantRoller.API.Data.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.UserPreference", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("RestaurantRoller.API.Data.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.UserRating", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Category", "Category")
                        .WithMany("UserRatings")
                        .HasForeignKey("CategoryId");

                    b.HasOne("RestaurantRoller.API.Data.Entities.Restaurant", "Restaurant")
                        .WithMany("UserRatings")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantRoller.API.Data.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Visit", b =>
                {
                    b.HasOne("RestaurantRoller.API.Data.Entities.Restaurant", "Restaurant")
                        .WithMany("Visits")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantRoller.API.Data.Entities.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Address", b =>
                {
                    b.Navigation("UsersWithHomeAddress");

                    b.Navigation("UsersWithWorkAddress");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Category", b =>
                {
                    b.Navigation("RestaurantCategories");

                    b.Navigation("Subcategories");

                    b.Navigation("UserRatings");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.Restaurant", b =>
                {
                    b.Navigation("OperatingHours");

                    b.Navigation("RestaurantCategories");

                    b.Navigation("Reviews");

                    b.Navigation("UserRatings");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("RestaurantRoller.API.Data.Entities.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Preferences");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
